### ISSUE TITLE
Encoding issue with slack notification

### ISSUE THREAD

**Issue by lyrixx** [umputun/remark42#1498] opened 2022-09-26 15:40 UTC
Hello,

We have installed your software on our website, and it looks like there is an encoding issue: 

![image](https://user-images.githubusercontent.com/408368/192320027-764e50b2-6145-4664-8857-b2f2ce5f9fa9.png)

As you can see, there is `&#39;` in the content.

Thanks

**Comment by paskal** [comment] 2022-10-02 17:48
I can't reproduce it neither in `umputun/remark42:latest` (`remark42 v1.10.1-6936268-20220606T10:17:25`) nor in `umputun/remark42:latest`. Could you please check the version you're running (it's written at the start of the container in the logs), and if it's not the latest (`v1.10.1`), then update it and try to reproduce the issue?

I presume it was fixed in https://github.com/umputun/remark42/commit/243c8356 (which is part of `master` and will be part of `v1.11.0` soon) and shouldn't reproduce in master. However, for me, it doesn't reproduce even with `v1.10.1`, so it might be something different, fixed earlier.

**Comment by damienalexandre** [comment] 2022-10-06 07:46
Thanks for testing it yourself, sorry you didn't reproduce! :fearful: 

We are waiting for `v1.11.0` and will report back here any change in this behavior! Thanks!

**Comment by paskal** [comment] 2022-10-11 20:46
`v1.11.0` is released, feel free to test it.

**Comment by paskal** [comment] 2022-10-29 21:14
Hi @lyrixx and @damienalexandre , can you reproduce the problem now?

**Comment by paskal** [comment] 2022-12-02 10:21
Please feel free to test with [v1.11.1](https://github.com/umputun/remark42/releases/tag/v1.11.1) now.

**Comment by damienalexandre** [comment] 2022-12-02 13:02
Thanks! The encoding issue is resolved, notifications are now properly displayed on Slack, thanks!

**Closed** 2022-12-02 13:16 UTC
Labels: bug, backend
