### ISSUE TITLE
remark42 randomly turns off

### ISSUE THREAD

**Issue by uPagge** [umputun/remark42#1461] opened 2022-08-21 20:05 UTC
For a week now I have been struggling with the problem that the container with the remark is falling. I don’t know why this happens, it didn’t happen before, I didn’t change the version, I didn’t change anything on the server, everything worked stably on version 1.10.1 since this version was released, but for a week now these containers have been falling for me and even restart always does not helps. Moreover, I have 2 remarks for different sites and they fall at the same time, and the remaining 7 containers that work for me in the same composition feel good.

Any ideas where to dig? There don't seem to be any error messages in the logs, or I'm looking in the wrong place. After manually launching remark42, it works for about a day and then crashes again

**Comment by uPagge** [comment] 2022-08-21 20:06
there are enough resources on the server

**Comment by paskal** [comment] 2022-08-21 21:33
We do need to see logs before the problem, there should be something. I assume docker-compose should have an option to save logs directly to files, please let me know if you need assistance setting it up.

**Comment by umputun** [comment] 2022-08-21 22:43
> I have 2 remarks for different sites and they fall at the same time, and the remaining 7 containers that work for me in the same composition feel good.

That is this "Same time" exactly? The only part what runs so rare (once a day) is the automatic backup, but in this case you should see log messages like `[WARN] auto-backup for <site> failed, <error>`. As remark42 starts (with `--dbg`) it also shows `[DEBUG] first backup for <site> at <date-time>`. In case if this `<date-time>` matches the time of the restart of container, your issue most likely related to this process. 

As @paskal correctly suggested, having the actual logs of the startup sequence, right before it failed and after the failure may help to diagnose the issue. Adding debug login may also help. Without this info all we can do is a guesswork, and my best guess - something is not right with mount related to backups, or the server/container runs out of some resources due to the backup. Anyway, pls run it with --dbg and share the log.

**Comment by paskal** [comment] 2022-08-22 20:03
I've checked, and there is no easy way to save logs to files apart from what `docker logs` show, so I don't think there is any additional setup aside from the standard one in docker-compose.yaml in that repo:

```yaml
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
```

**Comment by uPagge** [comment] 2022-08-23 18:52
Yes, that's how I have it set up. But I don't understand where these logs are stored and how to view them. As I said, the output of the docker logs remark42 command does not show any errors. It’s just that at some point the logs stop being written, apparently when the container is turned off, and it’s not clear why it doesn’t start again. Somehow this is all strange. I'll try to track the shutdown in real time a little later, maybe something will become clearer.

**Comment by paskal** [comment] 2022-12-02 18:29
Closing as non-reproducible for now. Feel free to reopen if you'll see such symptoms ever again.

**Closed by paskal** 2022-12-02 18:29 UTC
