### ISSUE TITLE
Image get cleaned up while waiting for CommitTTL to expire

### ISSUE THREAD

**Issue by ninedraft** [umputun/remark42#909] opened 2021-03-11 07:20 UTC
## How to reproduce
Copy [image](https://github.com/dropbox/kglb/blob/master/doc/kglb_open_arch.jpg) to clipboard and paste it In the comment post. Image renders properly on preview and after "Post" action. But after page reload post will contain a placeholder "can't load" image. 

## Details and examples

Post example
<https://radio-t.com/p/2021/03/09/prep-745/#comments>

![image](https://user-images.githubusercontent.com/12481320/110749289-03f13280-8252-11eb-9c75-a5210db58efa.png)

Problematic image xpath  `//*[@id="remark42__comment-6d119ea8-5d60-4302-8e45-53413f5c4b61"]/div[2]/div[1]/p[3]`: 
```html
<img src="https://remark42.radio-t.com/api/v1/picture/github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg" alt="image.png" loading="lazy">
```

Response <https://remark42.radio-t.com/api/v1/picture/github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg>:
```json
{
    "code": 18,
    "details": "can't get image github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg",
    "error": "can't get image file for github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg: can't get image stats for github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg: stat var/pictures.staging/github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/86/c14hklqhajfpucec9kdg: no such file or directory"
}
```

**Comment by akellbl4** [comment] 2021-03-11 07:49
@ninedraft hi! Thank you for the report. What browser exactly do you use? OS?
I've tried to reproduce it but the error on copy-paste. We should check why the error occurs. The most interesting thing to understand why you didn't see any error in the interface.

**Comment by ninedraft** [comment] 2021-03-11 07:51
@akellbl4 
>  What browser exactly do you use? OS?

+ Firefox 86
+ Manjaro Linux  20.2

**Comment by umputun** [comment] 2021-03-11 09:47
I can't reproduce the issue. The only valid reason for this behavior (except some obscure bug) I can think of - you started to write a comment and kept it open for a long time without hitting Send.  Not sure if this was the case - from my limited logs, all I can see is a preview request at 13:17:17, another preview at 13:17:22, one more at 13:20:24, one more at 13:20:37, and the actual post at 13:20:47. 

but after this moment I see odd things. @paskal  - I think you was the last working around image commits, pls see if something rings a bell:

in 8 minutes our GC kicked , at 13:28:07.648 `[INFO]  remove staging image var/pictures.staging/github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/86/c14hklqhajfpucec9kdg
, age 14m38.503965045`

and in a few seconds:

```
13:28:17.927 [WARN]  image commit error 1 error occurred:
     * failed to commit image github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg: failed to commit image github_3d624f3e7d0d60c
fcfa99b506fe245f1b678794f/c14hklqhajfpucec9kdg: rename var/pictures.staging/github_3d624f3e7d0d60cfcfa99b506fe245f1b678794f/86/c14hklqhajfpucec9kdg var/pictures/github_3d624f3e7d0d
60cfcfa99b506fe245f1b678794f/86/c14hklqhajfpucec9kdg: no such file or directory
```

To me, it looked like the commit happened after GC and failed due to this sad fact. I don't see how this possible, unless this post was opened for a really long time from the moment user uploaded the image till pressed Send.

@ninedraft - is this issue really reproducible? You can play on https://remark42.com/demo/ and see if you can get the same empty image result. 

_P.S. For readers of this ticket wondering how I can even see that log - no, remark42 doesn't phone home. I just happened to be one of the admins for that particular site._

**Comment by ninedraft** [comment] 2021-03-11 20:53
@umputun immediately got this error on demo remark instance:
![image](https://user-images.githubusercontent.com/12481320/110852360-53237b80-82c3-11eb-8817-5917c0feaefa.png)

Browser network log tells that it is  a HTTP error `413 Request Entity Too Large`. Actual request's `Content-Length` is 1481657 bytes. It looks like a normal behavior for me, but it doesn't match the problem, which caused me to start the issue

**Comment by umputun** [comment] 2021-03-11 20:57
well, this one is different and kind of expected. @akellbl4 it would be nice to show a proper error here on 413, like "image size exceeded blah blah"

**Comment by ninedraft** [comment] 2021-03-11 20:58
So, apparently image is visible now on the desktop browser, but is missing on mobile browser
![image](https://user-images.githubusercontent.com/12481320/110854004-5fa8d380-82c5-11eb-9611-ee701ab492d1.png)
 
![image](https://user-images.githubusercontent.com/12481320/110854149-954dbc80-82c5-11eb-8d61-8f79a7a714bf.png)

**Comment by umputun** [comment] 2021-03-11 20:59
Nah, likely from your local cache. I don't see it on the desktop browser either

**Comment by umputun** [comment] 2021-03-19 19:23
I have seen another similar case, but this one looks legit. I.e. it took really long for a user to post the message (23m)

```
2021/03/17 14:36:54.262 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (314) - 15.57501ms - {"text":"История одного бага в .NET 5\nhttps://habr.com/ru/post/547480\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)"}
2021/03/17 14:36:54.319 [INFO]  GET - /api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng - fa0f283ca946 - 200 (311041) - 3.80206ms
2021/03/17 14:37:13.145 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (314) - 2.106951ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480"}
2021/03/17 14:37:30.178 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (262) - 6.356995ms - {"text":"![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480"}
2021/03/17 14:37:44.137 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (314) - 77.455734ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480"}
2021/03/17 14:38:41.342 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (398) - 4.001565ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nНайти баг помог, как ни странно, сервер на Go"}
2021/03/17 14:40:45.241 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (405) - 19.52081ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nНайти баг, как это ни странно, помог сервер на Go"}
2021/03/17 14:45:41.078 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (517) - 14.509202ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nКак удалось отловить нетривиальный баг в обработке SSL-соединений (с помощью сервера на Go, как это ни странно)"}
2021/03/17 14:48:38.675 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (517) - 15.400267ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nКак удалось отловить нетривиальный баг в обработке SSL-соединений (как это ни странно, с помощью сервера на Go)"}
2021/03/17 14:50:52.186 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (554) - 15.26606ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nКак удалось отловить нетривиальный платформозависимый баг в обработке SSL-соединений (как это ни странно, с помощью сервера на Go)"}
2021/03/17 14:53:22.455 [INFO]  remove staging image var/pictures.staging/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/17/c195kkqhajfhbldotbng, age 16m30.696051501s
2021/03/17 14:58:25.282 [INFO]  POST - /api/v1/preview?site=radiot - fa0f283ca946 - 200 (554) - 14.206427ms - {"text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nКак удалось отловить нетривиальный платформозависимый баг в обработке SSL-соединений (как это ни странно, с помощью сервера на Go)"}
2021/03/17 14:59:10.753 [INFO]  POST - /api/v1/comment?site=radiot - fa0f283ca946 - 201 (1563) - 35.954121ms - {"title":"Темы для 746","text":"История одного бага в .NET 5\n![image.png](https://remark42.radio-t.com/api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng)\nhttps://habr.com/ru/post/547480\nКак удалось отловить нетривиальный платформозависимый баг в обработке SSL-соединений (как это ни странно, с помощью сервера на Go)","locator":{"site":"radiot","url":"https://radio-t.com/p/2021/03/16/prep-746/"}}
	* failed to commit image github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng: failed to commit image github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng: rename var/pictures.staging/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/17/c195kkqhajfhbldotbng var/pictures/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/17/c195kkqhajfhbldotbng: no such file or directory
2021/03/17 15:09:31.047 [WARN]  can't get image github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng - can't get image file for github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng: can't get image stats for github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng: stat var/pictures.staging/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/17/c195kkqhajfhbldotbng: no such file or directory - 400 (18) - /api/v1/picture/github_f022aa5dd492ec2b4d0ac0abfc595bed7aeb48de/c195kkqhajfhbldotbng - [rest/api/rest_public.go:345 api.(*public).loadPictureCtrl]
```

For this case, a possible solution could be to reset the cleanup timer on each preview. @paskal what do you think?

**Comment by paskal** [comment] 2021-05-16 21:18
The issue is not yet fixed, however, after #998 merge user won't be allowed to post a comment with a broken link to an image and will see an error in the interface. I'm looking into the original issue still.

**Comment by paskal** [comment] 2021-05-17 21:43
#992 is the proper fix for that issue.

**Comment by paskal** [comment] 2021-05-23 11:19
Here is a set of axioms true for remark42 at the current moment:

- cleanup timer for a particular image starts from the moment it's inserted into the system.
- when an image is posted in the comment, it's waiting for the comment edit period to expire and then committed to permanent storage if it's still in the comment after possible edits
- before #992 merge, cleanup timer for an image and its waiting period to commit it to permanent storage are not tied to each other in any way

The situation described in that issue happens when the image starts commit timer, and the cleanup timer expires sooner so that the image gets cleaned up before it gets to the permanent storage.

To solve it, #992 renews the cleanup timer the moment the image starts the cleanup timer so that permanent storage commit guaranteed to be done before staging storage cleanup kicks in for that image. Because it's easier to do after the change, also it renews the cleanup timer on a preview of the comment with the image to make sure the commentator wouldn't need to re-upload it after long comment editing before posting.

**Closed** 2021-05-24 22:34 UTC

**Comment by paskal** [comment] 2021-05-24 22:45
@ninedraft, thank you for the report. It was quite a ride to solve this one.
