### ISSUE TITLE
Something amiss with iframe height

### ISSUE THREAD

**Issue by brndnmtthws** [umputun/remark42#1521] opened 2022-10-27 15:09 UTC
I'm a big fan of Remark42, so thanks for creating it! Although nobody cares enough about my blog to leave a comment, I decided to add comments anyway in part because it's fun to do computers, and who knows maybe I will make a new friend on the internet.

Well anyway, about the problem: it seems that something is wrong with the height setting behaviour, where the height is set with `height: 100%` on the iframe style attribute if it loads out of the scroll area, but if you load _within_ the scroll area it sets the height correctly (in my case, `height: 354px`).

If I load the page normally, the height will be wrong. If I load the page, scroll to the bottom, then reload, it will calculate the correct height. I tried in a few browsers (Firefox, Chromium, Safari) and the same behaviour appears to occur in all three. [Here's a link to the example post below](https://brndn.io/posts/holiday-reading-list-2019/).

It's worth noting that I enabled lazy loading for images (`<img loading="lazy" />`) to make the pages load faster, but I suspect that might be messing it up. In any case, this seems like it shouldn't be happening. I'm using the `umputun/remark42:latest` Docker image, up to date w/ the latest as of now.

Here's a screenshot of the wrong height:

<img width="819" alt="Screen Shot 2022-10-27 at 10 00 31" src="https://user-images.githubusercontent.com/3129093/198326704-bdaad3e0-b7ba-4939-aa04-8619a18fb05a.png">

And here's a screenshot with the correct height:

<img width="901" alt="Screen Shot 2022-10-27 at 10 00 19" src="https://user-images.githubusercontent.com/3129093/198326788-1e752094-24d8-452f-8f30-ad383f9aa06a.png">

EDIT: After playing around a bit more, it seems that whether you have the iframe in the scroll view or not is irrelevant, I think it's entirely about whether or not the images have loaded.

**Comment by akellbl4** [comment] 2022-10-27 20:03
@brndnmtthws hey, thank you for filing the issue with all of the details. We'll try to solve it asap

**Comment by cooperaj** [comment] 2022-11-12 19:18
Hi, I've just upgraded from an older version (I'm very sorry but I was using master so I don't know exactly. It was probably 6+ months old tbh) and I'm now encountering this issue. Exact same symptoms as @brndnmtthws describes. You can see it happening [here](https://realmenweardress.es/2022/01/stpfmmp/)

**Comment by paskal** [comment] 2022-11-12 19:24
Please switch to v1.10.1 for now and in the meantime @akellbl4 is trying to find the fix.

**Comment by grayodesa** [comment] 2022-11-21 12:00
I have the same bug:
<img width="740" alt="remark-bug" src="https://user-images.githubusercontent.com/1035620/203047302-41dc2d6a-ec58-4168-ad9b-6653b1088e14.png">
Sometimes it is enough to refresh the page to fix it, sometimes it can be fixed by signing off and on again.
Here is the link https://blognot.co/113-it-mysli/

**Comment by grayodesa** [comment] 2022-11-21 12:10
Switched to v1.10.1 — works fine.

**Comment by snarkipus** [comment] 2022-11-23 03:23
Can also confirm that reverting to v1.10.1 resolves the issue - tracking this.

**Closed** 2022-11-30 00:12 UTC
Labels: bug, frontend

**Comment by brndnmtthws** [comment] 2022-12-01 13:01
The fix does indeed work, however I had to change the docker tag from `latest` to `master`, just in case anyone else bumps into this again. Presumably `latest` is the last release, as opposed to the most recent build from the master branch.

**Comment by paskal** [comment] 2022-12-02 10:22
[v1.11.1](https://github.com/umputun/remark42/releases/tag/v1.11.1) was released, so `latest` would work now as well.

**Comment by grayodesa** [comment] 2022-12-02 10:29
Upgraded to `latest`, works as intended.

**Comment by damienalexandre** [comment] 2022-12-02 13:34
We have another issue related to this, when the comment is spanning on multiple lines the iframe height is not increased anymore:

[remark42issue.webm](https://user-images.githubusercontent.com/225704/205302469-997919bb-a081-4dd4-9bc9-1725dc65d315.webm)

Example URL: https://jolicode.com/blog/we-are-open-sourcing-a-silly-slack-bot-guess-what-it-does

We run 1.11.1.

Thanks!
