### ISSUE TITLE
Both ordered and unordered lists produce errors

### ISSUE THREAD

**Issue by Ivanezko** [umputun/remark42#945] opened 2021-04-12 10:33 UTC
How to produce:
print 1 and point, then any text and enter
should appear ordered item 2, bu it doesnt and javascript-error instead https://cln.sh/cHifJR
same with unordered lists

**Comment by umputun** [comment] 2021-04-12 19:02
> should appear ordered item 2

Not sure why you expect 2 here. In MD `1.` on the next like is just fine for ordered. I don't think we ever had such an autoincrement in GitHub style

I can't reproduce the error. 401 is expected as you not authorized, but the other one (assertion failed) never happened in my tests.

**Comment by paskal** [comment] 2023-01-08 10:04
Resolving as we can't reproduce it, feel free to comment for reopening.

**Closed by paskal** 2023-01-08 10:04 UTC
Labels: frontend
