### ISSUE TITLE
Deliver frontend of Remark42 as npm package

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark42#1387] opened 2022-06-09 21:23 UTC
We could try to pack all of the frontend code into NPM package.
From benefits side that I see it would eliminate current SPA API and people who build SPA will have way of controlling the comments right from their code.

Requirements:
- pack code by widget with ability to lazy load the module out of the box
- provide all of the necessary methods for controlling the widgets
- pack file with API methods separately and expose API methods for outside use

Ideas:
- create wrappers for JS frameworks (for example remark42-react) for easier integration with them
- provide theme context which provides ability to modify theme of comments
- provide ability to replace components with user's own implementation

**Comment by Reeywhaar** [comment] 2022-06-09 21:28
Dupe of https://github.com/umputun/remark42/issues/240 :-)

**Closed** 2022-06-09 21:37 UTC
Labels: discussion, frontend
