### ISSUE TITLE
Mobile navigation to comment doesn't work for hidden comments

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#82] opened 2018-06-15 18:11 UTC
If a comment not shown on the first screen, anchor navigation doesn't work.

For example, this link (on mobile) may not work for some sortings (best, maybe others) https://radio-t.com/p/2018/06/12/prep-602/#remark42__comment-68d9aace-67f7-47b6-9f6c-ae8bdbe7fbdd

**Comment by Guria** [comment] 2018-06-23 15:04
@umputun I guess it could be solved if render all comments even on mobile if remark comment link is present in url.
Of course it is preferable to check if comment is already visible first, but it's would be much harder to implement.

**Comment by igoradamenko** [comment] 2018-06-23 18:57
@Guria, great idea, thanks.

I'm not sure that it would be much harder to implement logic of checking, because we can just check a position of comment in the list (yep, it can be a reply, but it isn't hard to find root comment and get its position). If it's lower that limit of showing — we don't need to do anything. If it's not, we just increase the limit, and everything should work fine.

**Comment by jackburg** [comment] 2018-07-13 20:51
@Guria , @igoradamenko I've created a fix addressed to this issue, please take a look.

![2018-07-13 23 47 30](https://user-images.githubusercontent.com/7156424/42713268-85eb141c-86f7-11e8-8924-5f154ed3bc14.gif)

**Comment by paskal** [comment] 2020-04-13 12:40
Can reproduce in current master with link above.

**Comment by Yuriy-Karpov** [comment] 2021-05-06 17:56
hi, here's a fix that should fix this https://github.com/umputun/remark42/pull/983

**Comment by paskal** [comment] 2023-01-08 09:15
It works in the latest stable version, resolving.

**Closed by paskal** 2023-01-08 09:15 UTC
Labels: bug, help wanted, frontend
