### ISSUE TITLE
Avatars using old path after moving remark42 to subdomain server

### ISSUE THREAD

**Issue by leem32** [umputun/remark42#815] opened 2020-11-16 13:56 UTC
I've moved Remark42 to a subdomain and everything worked OK, except the comment avatars are still using the old path causing them to 404.

Comments used to be loaded at: https://mywebsite.com/comments/

But now they are loaded at: https://comments.mywebsite.com/

New avatars are working fine and use the new path e.g https://comments.mywebsite.com/api/v1/avatar/bfd6920290b08974a9bef14fbdd6.image

But avatars which existed before I moved to a subdomain still use the old path:
https://mywebsite.com/comments/api/v1/avatar/d2df009d39b09a79d040d45aeb484a.image

Is there any way I can fix this?

I can't delete all the old comments as they add value.

**Comment by leem32** [comment] 2020-11-18 15:44
I've tried destroying remark image and container, backup, and restore comments, neither worked.

Is updating avatar paths of old comments not possible??

I'll just have to delete them all and start again if that's the case.

**Comment by paskal** [comment] 2020-11-18 16:12
As a side note, would be amazing if you’ll write down your findings on domain change to documentation.

**Comment by leem32** [comment] 2020-11-19 12:43
@paskal, will do.

At the moment I'm having trouble removing comments.

If I stop remark42, delete all remark comment backups inside the container, delete the container, delete the remark image, delete the build cache e.g `docker system prune -a --volumes` and then do a `docker-compose pull && docker-compose up -d`
the comments still load in the browser WTF.

Even if I load the comments in a browser that has never loaded Remark42 before, the comments still appear.

**Comment by leem32** [comment] 2020-11-19 14:13
Deleting then reinstalling the Remark42 git repo on the host removed comments. 
There is a copy of all comments inside the remark42 git repo on the host which I wasn't aware of.

**Comment by umputun** [comment] 2020-11-19 18:01
all comments stored outside of the container on the mounted volume. This is done by design, to survive container removal/recreation. This is not "inside the remark42 git" but in the place defined by the configuration under `store.bolt.path` (default `./var`) for the comments and `image.fs.path` (default `./var/pictures`) for images. 

Backup is just a backup, not the primary storage. Removing it won't affect loaded comments, but rather the ability to restore from this removed backup file.

_Both params are listed in the README._

**Comment by leem32** [comment] 2020-11-19 18:20
I fixed the comment avatar errors by making a backup of comments, unzipping them and changing the `picture` path to the new server path. This didn't work for all comments however so I changed the `picture` path to an empty string and Remark42 then uses the default avatar.

Not perfect, but it removed the `404` errors and I get to keep all old comments. New comments do show user's avatars correctly.

**Comment by leem32** [comment] 2020-11-20 13:18
I recently had to move Remark42 over to a new server (mywebsite.com/comments -> comments.mywebsite.com).
The move was relatively straight forward, but there are a couple of things that are worth documenting such as setting the new paths for the comment avatars.

1. Update server Conf file with the new Remark42 server path:
The below example is for Nginx.

```nginx
server {

  listen 443 ssl http2;

  server_name comments.{{ domain_name }};

  ssl_certificate      /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
  ssl_certificate_key  /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;

  location ~ /.*(\.git|\.txt|\.log) {
      access_log off;
      log_not_found off;
      deny all;
  }

 location / {
    proxy_redirect          off;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        Host $http_host;
    proxy_pass              http://{{ domain_name }}:8080/;
 }

 access_log   /var/log/nginx/remark42.log;

}

server {
  listen 80;
  server_name comments.{{ domain_name }};
  return      301 https://comments.{{ domain_name }}$request_uri;
}

```


2. Update Remark42 with new `REMARK_URL` server path e.g https://comments.mywebsite.com You also need to set `ADMIN_PASSWD` so you can make a backup of comments.

3. Update Remark with the new config: `docker-compose pull && docker-compose up -d`

4. Update the frontend with your new server path

```javascript

var remark_config = {
  host: "https://comments." + window.location.hostname,
  ...
}

```

You should now see comments on the webpage using the new path except the comment avatars will be missing and the console will show a `404` status code for the avatars.

To remove the `404` errors you need to unzip the comments file and change the avatar paths manually.

Here's the steps to display comment avatars still using the old Remark42 server path:

5.1. Backup comments: 
`docker exec -it remark42 backup -s {your site id} --admin-passwd {ADMIN_PASSWD}`
5.2. Open Remark42 container: 
`docker exec -it {container_id} /bin/sh`
5.3. Get backup file name: 
`ls -la var/backup/`
5.4. Unzip backup: 
`gzip -d var/backup/userbackup.gz`
Change the comments to use the new path
For example here I am changing the Remark42 path from mywebsite.com/comments/ to the new path comments.mywebsite.com/
you can remove `-i` from the `sed` command to perform a trial run.
`sed -i 's+mywebsite.com/comments/+comments.mywebsite.com/+g' userbackup`
5.5. Zip backup: 
`gzip var/backup/userbackup`
5.6. Set permissions: 
`chown app:app var/backup/userbackup.gz`
5.7. Exit Remark container and return to host: 
`exit`
5.8. Restore comments backup: 
`docker exec -it {container_id} restore -f userbackup.gz -s {your site id}`

Done

**Comment by umputun** [comment] 2020-11-20 18:09
thx. Btw, have you checked this one (remap functionality)? 

https://github.com/umputun/remark42/issues/412

**Comment by leem32** [comment] 2020-11-21 16:16
No, I didn't try that.

**Comment by paskal** [comment] 2020-11-21 17:08
I would be extremely grateful if you’ll be able to test that mechanism and post your notes, I’ll publish it in the documentation then.

**Comment by paskal** [comment] 2020-11-30 09:41
@leem32 #810 seem to be covering the thing you had to do, I'll repost it to documentation shortly. Please let me know if you still have any trouble after migration of avatars after using that instruction.

**Comment by paskal** [comment] 2023-01-08 10:23
Resolving this issue, I hope the current documentation after #828 covers this case well enough.

**Closed by paskal** 2023-01-08 10:23 UTC
