### ISSUE TITLE
Github login on mobile redirects to /web/iframe.htm

### ISSUE THREAD

**Issue by rubentorresbonet** [umputun/remark42#870] opened 2021-02-04 08:21 UTC
I did a fresh install on my gatsby site and this issue only happens with github on mobile (android) so far:

1. Open android chrome and go to my site.
2.  Login with github (github app or web version)
3. Authorize (I see on the bottom: authorizing will redirect to https://remark42.mydomain.com)
4. I'm redirected to https://remark42.mydomain.com/web/iframe.html?selfClose. Here I can see only the comment box, not my site, and commenting will end in a "Forbidden" message
5. Going back to my site in the previous will show the outdated view with the login options available, including github
6. Manually refreshing the page will show the right logged in state and allows for posting

Now, if it was already authorized, I does not redirect me to the iframe but I need to refresh manually the site to work.

On desktop this flow works well.

Not sure if related, but I had to modify the client javascript so it loads the embed.js instead of embed.mjs. The last one is a 404. So the only thing I did is to remove the "m" from the client javascript.

Thanks!

**Comment by akellbl4** [comment] 2021-02-04 09:24
Hi @rubentorresbonet 
I could assume it's related to our `selfClose` mechanism and smth won't work in Chrome on Android. I'll investigate this.
What version of Android and Chrome do you use?

**Comment by rubentorresbonet** [comment] 2021-02-04 09:31
Hi Pavel,
Thanks a lot!
I'm quite updated, using Android 10 and Chrome released on February 1st
2021.
Can I help you debug this issue somehow?

**Comment by akellbl4** [comment] 2021-02-04 10:56
I'll try to reproduce it with BrowserStack

**Comment by akellbl4** [comment] 2021-02-05 10:12
As I see you are using `master` version of Remark42. It was a bug in master check if the problem is disappeared.
Also, I'll check why you have 404 when the browser loads embed.mjs because

**Comment by rubentorresbonet** [comment] 2021-02-05 10:32
I think your previous message cut off.
I tried updating the docker image but it doesn't seem like it did much?
`~/remark42$ docker pull umputun/remark42:latest
latest: Pulling from umputun/remark42
Digest: sha256:99e1cce0660ddff18afca4244422963256f050424cc0ed9fe9b0c6f8eeff9bcb
Status: Image is up to date for umputun/remark42:latest
docker.io/umputun/remark42:latest`

**Comment by rubentorresbonet** [comment] 2021-02-05 10:38
Nevermind, I had to use docker-compose pull and restart it.
Indeed, the frame closes automatically. However, the component doesn't reload and I appear as logged out still. I need to manually refresh the page to show the logged in status.
Any idea where's that coming from?

**Comment by akellbl4** [comment] 2021-02-05 10:51
I've found out why you don't have "mjs". You use the latest version of Remark but docs already updated for the next release.

I'll try to reproduce your bug on the latest version, bug fix could be delivered just with the new version.
Could you try to run the latest version from master `umputun/remark42:master` and check if the bug still reproduces?

**Comment by rubentorresbonet** [comment] 2021-02-07 15:49
@akellbl4 I updated my docker image to master and sadly still the mobile version needs to manually refresh after logging in to github

**Comment by akellbl4** [comment] 2021-02-08 07:09
Okay, I need more time to dive deeper in the problem.
It could be easier if you post model of your smartphone and OS version. I tried to reproduce problem on Samsung S20, Google Pixel, and One Plus with Android 10 and 11. On these smartphones in Chrome everything works just fine.
Maybe you are using any kind of addons/extentions which are blocking closing of the tab?

**Comment by rubentorresbonet** [comment] 2021-02-08 15:41
I can't use addons on android chrome.
Can you try to reproduce it here? Just go to the bottom and press "show
comments". Then login to github.

The window should close but you'll need to refresh for the logged in status
to kick in.

https://thegamedev.guru/unity-performance/occlusion-culling-tutorial/#level-3-the-big-picture

Thanks

**Comment by akellbl4** [comment] 2021-02-09 09:42
I tried to do it and I was redirected immediately back to the page on Samsung and Pixel.
Let's try to debug on your device. Try to connect your device with this [manual](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) and check the console if some errors or warnings are appearing there.

**Comment by rubentorresbonet** [comment] 2021-02-09 09:46
Yes, I'm also redirected back to it.
But the question is: are you logged in through github immediately or do you
need to refresh the browser to take effect?

**Comment by akellbl4** [comment] 2021-02-09 09:53
As I see yes.
https://cln.sh/GqrFPb

**Comment by rubentorresbonet** [comment] 2021-02-09 09:59
Aha! I uninstalled the github android app and it worked.

Maybe the github app interferes with that. Can you try with the github
android app enabled and logged in?

Thanks

**Comment by akellbl4** [comment] 2021-02-09 10:17
Not sure if I can install GitHub app in BrowserStack but I will try to do it later

**Comment by paskal** [comment] 2023-01-03 20:37
Resolving this issue for lack of data now, please reopen if anyone could reproduce that problem.

**Closed** 2023-01-03 20:47 UTC
