### ISSUE TITLE
Not working on chrome due to lack of SameSite=None attribute

### ISSUE THREAD

**Issue by aca** [umputun/remark42#784] opened 2020-10-04 19:44 UTC
I think I have issue with all chromium based browser. (Tried brave, and mobile chrome)
With firefox everything is working just fine.

issue page: https://aca.github.io/2020_10_hello_world.html

If I try to login anonymously It prints
![image](https://user-images.githubusercontent.com/50316549/95025464-e200ec00-06c4-11eb-81cd-ed34cf67fd25.png)

If I try to log out, It prints some cookie error.
```
2020/10/04 19:32:07.882 [INFO]  logout not allowed - token cookie was not presented: http: named cookie not present - 403 - /auth/logout?site=aca.github.io [caused by auth/provider/oauth2.go:220 provider.Oauth2Handler.LogoutHandler]
```

GIthub login also doesn't work.

```
$ ./remark42 version
remark42 master-71dcb13-20200426T12:41:26
```

**Comment by umputun** [comment] 2020-10-04 20:13
it doesn't work in any browser for me, not just chromium-based. Probably due to mismatch in domains? I see your remark42 lives on https://acadx0.mooo.com but the site itself on https://aca.github.io

If you do https://acadx0.mooo.com/web/ you will see everything works on all browsers, including chromium-based.

**Comment by aca** [comment] 2020-10-05 03:36
@umputun 
Yes I hosted it on other domain as I cannot serve remark on github.io.
If I'm wrong or, if there is any workaround to integrate remark with github.io, please let me know.

aca: https://aca.github.io
remark: https://acadx0.mooo.com (with caddy reverse-proxy for https)

It seems it's working fine with ms edge(which is chromium as far as I know).
I've rechecked with firefox. It's working fine. What is going on?

**Comment by umputun** [comment] 2020-10-05 04:13
> What is going on?

Not sure. On FF I see cookies set as expected, however not on safari or chrome. 

@Mavrin something prevents browser to set cookies and I'm not sure what exactly. Can you take a look? 
@paskal in case you have some bright ideas pls share.

**Comment by aca** [comment] 2020-10-05 04:39
@umputun I found out what's going on.


Chrome set samesite default to Lax, and Firefox set it to None (which will change in the future).
I patched this line 
https://github.com/umputun/remark42/blob/ecb146bf20ba7f6f6ab2ec82e22e1b3de8dc9823/backend/vendor/github.com/go-pkgz/auth/token/jwt.go#L234

with
```
	jwtCookie := http.Cookie{
		Name: j.JWTCookieName, Value: tokenString, HttpOnly: true, Path: "/",
    MaxAge: cookieExpiration, Secure: j.SecureCookies, SameSite: http.SameSiteNoneMode,
	}
	http.SetCookie(w, &jwtCookie)

	xsrfCookie := http.Cookie{
		Name: j.XSRFCookieName, Value: claims.Id, HttpOnly: false, Path: "/",
		MaxAge: cookieExpiration, Secure: j.SecureCookies, SameSite: http.SameSiteNoneMode,
	}
```

So, to fix it properly It seems we need to patch go-pkgz. 
If you are OK, I will send pr later on.

**Comment by umputun** [comment] 2020-10-05 04:44
good catch. 

> If you are OK, I will send pr later on.

yes, pls. It will be also nice to add samestie value as a param, i.e. pass in `http.SameSite`

**Comment by janikvonrotz** [comment] 2020-11-11 08:49
@aca Were you able to submit the patch? Looking forward to fix this issue.

**Comment by OnlineBiblioTK** [comment] 2020-12-02 00:45
Looking

**Comment by umputun** [comment] 2021-01-15 04:24
@aca - I have added SameSite parameter to auth options. You can pass it as `--auth.same-site` or env:AUTH_SAME_SITE with values default/none/strict/lax.

**Comment by OnlineBiblioTK** [comment] 2021-01-15 17:29
[...]
image: umputun/remark42:master
[...]
environment:
- AUTH_SAME_SITE=none
[...]

No effect for me in Сhrome.
Example: https://your-lib.pl/200/e-ksiazka-48644215.html

**Comment by umputun** [comment] 2021-01-15 17:46
thx, I think i figured and fixed the root cause. pls, give it a try (update umputun/remark42:master image)

**Comment by OnlineBiblioTK** [comment] 2021-01-15 17:50
> thx, I think i figured and fixed the root cause. pls, give it a try (update umputun/remark42:master image)

It works! Thank you!

**Comment by vadamk** [comment] 2023-01-12 14:04
Still can not auth with SameSite=None
If SameSite=None is set, the cookie "Secure" attribute must also be set (or the cookie will be blocked).

**Comment by paskal** [comment] 2023-01-15 19:16
Secure would be set if your Remark42URL starts with `https://`. Please verify if it works for you when you change the URL to start with `https://`, and please feel free to update the documentation in place you would expect to see that information.

**Comment by paskal** [comment] 2023-03-11 00:27
Resolving, as I presume my last comment solved the issue.

**Closed by paskal** 2023-03-11 00:27 UTC
Labels: backend
