### ISSUE TITLE
User comments counter includes deleted comments

### ISSUE THREAD

**Issue by daniloarcidiacono** [umputun/remark42#1480] opened 2022-09-11 09:48 UTC
As per title, the user comments counter does not skip deleted comments. Is that the intended behaviour?
I've found a similar issue https://github.com/umputun/remark42/issues/261 but I don't think caching is the culprit.

The counting algorithm infact is based on `userBucketName` bucket:

```go
err = bdb.View(func(tx *bolt.Tx) error {
	usersBkt := tx.Bucket([]byte(userBucketName))
	userIDBkt := usersBkt.Bucket([]byte(req.UserID))
	if userIDBkt == nil {
		return fmt.Errorf("no comments for user %s in store for %s site", req.UserID, req.Locator.SiteID)
	}
	stats := userIDBkt.Stats()
	count = stats.KeyN
	return nil
})
```

which is not updated in `deleteComment`:

```go
func (b *BoltDB) deleteComment(bdb *bolt.DB, locator store.Locator, commentID string, mode store.DeleteMode) error {
	return bdb.Update(func(tx *bolt.Tx) error {
		postBkt, e := b.getPostBucket(tx, locator.URL)
		if e != nil {
			return e
		}

		comment := store.Comment{}
		if e = b.load(postBkt, commentID, &comment); e != nil {
			return fmt.Errorf("can't load key %s from bucket %s: %w", commentID, locator.URL, e)
		}

		if !comment.Deleted {
			// decrement comments count for post url
			if _, e = b.count(tx, comment.Locator.URL, -1); e != nil {
				return fmt.Errorf("failed to decrement count for %s: %w", comment.Locator, e)
			}
		}

		// set deleted status and clear fields
		comment.SetDeleted(mode)

		if e = b.save(postBkt, commentID, comment); e != nil {
			return fmt.Errorf("can't save deleted comment for key %s from bucket %s: %w", commentID, locator.URL, e)
		}

		// delete from "last" bucket
		lastBkt := tx.Bucket([]byte(lastBucketName))
		if e = lastBkt.Delete([]byte(commentID)); e != nil {
			return fmt.Errorf("can't delete key %s from bucket %s: %w", commentID, lastBucketName, e)
		}

		return nil
	})
}
```

Thanks

**Comment by paskal** [comment] 2022-09-12 21:14
Thanks for the report! That is a duplicate of #273, feel free to repost your message there if it adds to the discussion.

**Closed by paskal** 2022-09-12 21:14 UTC
