### ISSUE TITLE
False-positve on image removal from the staging

### ISSUE THREAD

**Issue by umputun** [umputun/remark42#584] opened 2020-01-27 19:03 UTC
I have seen the missing images in several comments. This is a rare event but still

I think, there are two reasons for this:

1. sometimes cleanup activated on exact TTL and commit may be delayed for at least 10ms
1. the logic of submitting multiple ids is sequential and blocking. I didn't expect it to delay commit significantly and still don't understand how this even possible, but I see an example of a failing attempt to commit already removed staging image with a strangely long delay between cleanup (07:46:34.384) and commit (07:47:22.677)

**Comment by Infinoid** [comment] 2020-04-01 14:18
I had this problem while using the `umputun/remark42:latest` docker image, and then saw this ticket.  So I updated to `umputun/remark42:master`, and just saw the problem again.  So I think the bug is still present.

I've reproduced the problem 3 times in a row; do you have any ideas for things I can try?

**Comment by paskal** [comment] 2020-04-01 14:41
@Infinoid could you please post here the app version which is printed at the beginning of the log after the container starts?

**Comment by Infinoid** [comment] 2020-04-01 14:42
```
init container
set timezone America/Chicago (Wed Apr  1 09:26:06 CDT 2020)
custom APP_UID not defined, using default uid=1001
execute /srv/init.sh
prepare environment
execute "/srv/remark42 server"
remark42 master-10c1aa9-20200401-02:36:51
2020/04/01 09:26:07.238 [INFO]  {cmd/server.go:253 cmd.(*ServerCommand).Execute} start server on port 8080
```

**Comment by paskal** [comment] 2020-04-01 14:51
As this issue might be tied to settings values, could you please share a non-sensitive part of your docker-compose.yml file?
I think it would be better to upload it to Pastebin to prevent having a commend with 50 lines of code there.

I’ve worked on image code recently and will try to write a failing test case with this problem reproduction if @umputun was right about the root cause.
But it’s very unlikely because of the applied fix until the commit time is very small and the difference between its value and 3x its value is neglectable in the scale of CPU/io, so I assume anything higher than 100ms couldn’t be a problem.

**Comment by Infinoid** [comment] 2020-04-01 14:56
https://gist.github.com/Infinoid/5e290480d67a586870b071cb7bb00967

**Comment by Infinoid** [comment] 2020-04-01 15:00
I am doing the following to reproduce the issue:

1. Type a sentence of text into the comment field
2. Hit enter a couple of times
3. Find an image in google image search, copy image, paste it into the comment box
4. Click Send
5. Wait 30-40 minutes
6. See a log entry about the image being cleaned up (see below)
7. Refresh page and see my comment has a broken icon where the image was

The log entry looks like this:
`2020/04/01 09:14:35.536 [INFO]  {image/fs_store.go:128 image.(*FileSystem).Cleanup.func1} remove staging image var/pictures.staging/[[[my github id]]]/69/bq29imia0kee9rbpqs00, age 36m1.228272714s`

**Comment by paskal** [comment] 2020-04-01 15:06
Please post the log with the problem reproduction as well if you can. There should be a “commit” action before the clean up, if it’s not there it would be the reason, and if it there - something with it is wrong.

**Comment by Infinoid** [comment] 2020-04-01 15:10
I tried to reproduce the problem a 4th time, and I saw this log message 12 minutes after posting the comment:

`2020/04/01 10:00:53.152 [DEBUG] {image/fs_store.go:74 image.(*FileSystem).Commit} Commit image [[[my github id]]]/bq2ajc24vh1p4nbefc2g`

And it looks like the picture was moved from `pictures.staging/` into `pictures/`.  This did not happen the previous 3 times I tried; the image was cleaned up without being committed.  It's the first time I have seen this message.

I think the problem may be caused by restarting the docker container during the staging time period.  I did not restart it this time, and it worked.  But in the past, I have been restarting it a lot as I work on configuring email notifications and such.

**Comment by Infinoid** [comment] 2020-04-01 15:15
I am trying to test that now.  I posted one comment with an image, restarted the docker container, and posted another comment with another image.  I want to see if the first image is deleted and the second one remains valid.

**Comment by umputun** [comment] 2020-04-01 15:23
restarting container in the middle of the two-stage commit will lead to this issue for sure because the second stage timer won't be activated and the image will be garbage collected eventually. 

Making this logic persistent across restarts will be tricky. However, we may handle it in the main signal catcher and activate all pending commit on sigterm.

**Comment by Infinoid** [comment] 2020-04-01 15:26
Well, the workaround is simple: leave the container alone. :)

Thanks, this is making more sense now.

**Comment by Infinoid** [comment] 2020-04-01 15:41
Yep.  I confirmed that my issues are caused by restarting the docker container.

![image](https://user-images.githubusercontent.com/50254/78157038-81d77780-740d-11ea-93af-291ed0667ac9.png)

The first and third images were allowed to commit normally; the second one was the victim of a restart.

**Comment by umputun** [comment] 2020-04-01 15:44
the issue is kind of expected, but still. @paskal - would you like to handle this one?

**Comment by paskal** [comment] 2020-04-01 17:05
Commit on the start of app should fix that, it’s really nice we found this issue. I’ll tackle it.
Thank you @Infinoid!

**Comment by umputun** [comment] 2020-04-01 17:07
@paskal pls note - this may commit things we don't like to commit, for example, images without the actual comment (i.e. a comment with image preview was never posted)

**Comment by paskal** [comment] 2020-04-11 12:45
I see that in case of ungraceful shutdown image code dies [there](https://github.com/umputun/remark42/blob/98b77f076caf3b92fd1eb024274e00d6b836543a/backend/app/store/image/image.go#L93-L95) when with graceful shutdown it correctly stores all hanging images [there](https://github.com/umputun/remark42/blob/98b77f076caf3b92fd1eb024274e00d6b836543a/backend/app/store/image/image.go#L151).

I give some thought to what we can do in case of an ungraceful shutdown and I came up with three variants:

1. Save all images from staging on startup.
We'll potentially commit unused images to the storage which will hit some installation someday for sure.
1. On startup go through all comments by some criteria and commit all images from them.
Very complex and I can't figure out how to make it fast: remark42 can be started a year after ungraceful shutdown and it would need to look up images for the TTL period not before the start moment but before the last submitted comment. It would spend resources going trough potentially big amounts of comments on each start of the application and also would complicate code significantly. 
1. Document current behavior.
Write in readme side effects of an ungraceful shutdown of the application.

If I am right about what I wrote above, my vote goes for third variant, doing nothing but documenting current behavior of remark42 properly.

**Comment by umputun** [comment] 2020-04-14 21:37
I think 2 not as bad as you think. All it needs:

1. Check if any files in staging. If nothing in - no action needed
1. If something in, pull LastComments with from=<time stamp of the oldest image>
1. For each comment analyze if any of the images in, and commit if the match found

note: I described it in terms of FS store, but obviously we will need to promote some "getStagingImages" of some sort to the interface.

_I don't think this one is required for 1.6. The issue is not critical and we can handle it latter, as a hotfix or even for 1.7_

**Comment by paskal** [comment] 2020-04-18 15:59
> restarting container in the middle of the two-stage commit will lead to this issue for sure because the second stage timer won't be activated and the image will be garbage collected eventually.
> 
> Making this logic persistent across restarts will be tricky. However, we may handle it in the main signal catcher and activate all pending commit on sigterm.

To clarify, I fixed that in #658. Now SIGTERM would trigger committing all images which are currently in staging.

**Closed** 2020-04-23 05:52 UTC
Labels: backend, bug

**Comment by paskal** [comment] 2020-04-23 17:01
@Infinoid would you be so kind as to test if current master fixed docker restart scenario for you?

**Comment by Infinoid** [comment] 2020-04-24 12:02
I pasted an image into the comments field, then refreshed the page without posting that comment.
I pasted a second image into the comments field, and posted the comment.

Then I restarted the docker container.  I see "start pictures cleanup, staging ttl=12m30s" in the log.

7 minutes 30 seconds after docker restart, I see "image ids extracted" and "Commit image" log messages, indicating that the second image was committed.

12 minutes 30 seconds after docker restart, I see a "removing staging image" message, indicating that the first image was discarded.

After refreshing the page again, the second image is still present in the comment.  So that seems to be working great.  Thanks!
