### ISSUE TITLE
Page shows form with already published comment

### ISSUE THREAD

**Issue by valichek** [umputun/remark42#630] opened 2020-03-31 11:55 UTC
These are steps I did (but not tried to reproduce)

Entered page 
Authenticated with github. 
Wrote comment. 
Clicked preview.
Published comment. 
Closed page.
After about 3-4 hours came back to check my comment.
And it showed me the publish form with my comment.
Also it shows me it every time I do page refresh.

chrome 80.0.3987.149, osx

<img width="814" alt="Снимок экрана 2020-03-31 в 14 43 17" src="https://user-images.githubusercontent.com/7127622/78022925-6d887180-735e-11ea-90eb-5fa3f82c4f0a.png">

**Comment by umputun** [comment] 2020-04-03 02:57
@akellbl4 is #634 supposed to fix the issue? With the current master, I still see it

**Comment by akellbl4** [comment] 2020-04-03 04:16
@umputun did you test it in the way which was described in issue or you did smth different? I tested it on remark42.com/demo and it works well. Of course, you don't need to wait a few hours :)

**Comment by umputun** [comment] 2020-04-03 04:18
all I did is started a local container, authed with dev, wrote a comment and refreshed the page. After page's refresh, I can see the comment in the entry box.

**Comment by umputun** [comment] 2020-04-03 04:22
however, I can't reproduce it on demo site. It seems to clear the comment on submit, but it still filled in case of page refresh prior to submitting. Not sure if expected

**Comment by akellbl4** [comment] 2020-04-03 04:36
Yep. I don't clear the field before it was sent because I don't know what caused refresh of a page (auth or you refreshed it manually).
Actually I think it could be a feature, because we save your comment if you accidentally reload a page or if you started to write comment leave a page and return to it after some time.

If we don't need behavior like this I think I don't should save a value of field to local storage if a user logged in.

**Comment by umputun** [comment] 2020-04-03 05:27
> Actually I think it could be a feature, because we save your comment if you accidentally reload 

Yep, same thing. It is actually a good thing to have. The only problem with this – somehow during my testing of a different ticket (about image uploads) I've seen the text staying in even after submit.

**Comment by akellbl4** [comment] 2020-04-03 08:23
I'll check it.

**Comment by akellbl4** [comment] 2020-04-08 12:12
@umputun could you please give me an example of reproducing this? Now I see after putting an image in a comment it doesn't save an image reference between refresh of a page.

**Comment by umputun** [comment] 2020-04-09 08:13
I didn't do anything special. Just started the container and see the last published comment from a week ago right away

<img width="866" alt="dd6zz6d9gq-20200409-031234" src="https://user-images.githubusercontent.com/535880/78873198-16deff80-7a10-11ea-8028-a407a4d3893d.png">

**Comment by umputun** [comment] 2020-04-09 08:16
However, can't reproduce it anymore

**Comment by akellbl4** [comment] 2020-04-09 09:49
@umputun yep. I think it's because a comment was saved before my fix and I didn't implement cleaning of comments saved before.
I want to ask, how long do images that weren't posted store at the backend? I don't know, but I think these images could be removed if they aren't posted.

**Comment by umputun** [comment] 2020-04-09 17:11
>  how long do images that weren't posted store at the backend? I don't know, but I think these images could be removed if they aren't posted.

images submitted to the staging right away and committed (moved) to the permanent location on comment's save. In fact, it is a little bit more complicated because we have to postpone the commit till the edit window expired. But the bottom line - not committed images will be removed automatically by our internal garbage collector.

pls note: links to images are permanent, i.e. committed image will have the same url as submitted one.

hope it helps.

**Comment by umputun** [comment] 2020-04-12 22:04
@valichek I don't see this issue anymore. If all good, feel free to close this one

**Closed** 2020-04-13 06:38 UTC
Labels: bug, frontend
